motion:
  image: easypi/motion-arm
  ports:
    - "8080:8080"
    - "8081:8081"
  volumes:
    - ./motion.conf:/etc/motion/motion.conf
    - ./data:/var/lib/motion
    - /etc/localtime:/etc/localtime
  devices:
    - /dev/video0:/dev/video0
  restart: always
