version: '2'

services:
  drone-server:
    image: easypi/drone-arm
    ports:
      -  "8000:8000"
    volumes:
      - ./data:/var/lib/drone
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=drone.easypi.pro
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=https://gogs.easypi.pro
      - DRONE_SECRET=0123456789
    restart: always

  drone-agent:
    image: easypi/drone-arm
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=0123456789
    depends_on:
      - drone-server
    restart: always
